name: Check

on:
  pull_request:

  push:
    branches:
      - main # Check branch after merge
      - test

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
#  check-code-style:
#    name: Code Style
#    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
#    with:
#      cmd: sbt validateCode

  changes:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      samples: ${{ steps.filter.outputs.changes }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            java-chatroom: java/chatroom/**
            java-compile-di: java/compile-di/**
            java-dagger2: java/dagger2/**
            java-ebean: java/ebean/**
            java-fileupload: java/fileupload/**
            java-forms: java/forms/**
            java-grpc: java/grpc/**
            java-hello-world: java/hello-world/**
            java-jpa: java/jpa/**
            java-pekko-cluster: java/pekko-cluster/**
            java-rest-api: java/rest-api/**
            java-starter: java/starter/**
            java-streaming: java/streaming/**
            java-websocket: java/websocket/**
            scala-anorm: scala/anorm/**
            scala-chatroom: scala/chatroom/**
            scala-compile-di: scala/compile-di/**
            scala-fileupload: scala/fileupload/**
            scala-forms: scala/forms/**
            scala-grpc: scala/grpc/**
            scala-hello-world: scala/hello-world/**
            scala-isolated-slick: scala/isolated-slick/**
            scala-log4j2: scala/log4j2/**
            scala-macwire-di: scala/macwire-di/**
            scala-rest-api: scala/rest-api/**
            scala-secure-session: scala/secure-session/**
            scala-slick: scala/slick/**
            scala-starter: scala/starter/**
            scala-streaming: scala/streaming/**
            scala-tls: scala/tls/**
            scala-websocket: scala/websocket/**

  java-chatroom:
    name: "Java :: Chatroom"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'java-chatroom')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: java/chatroom
      cmd: |
        ./test.sh --sample=java/chatroom --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  java-compile-di:
    name: "Java :: Compile DI"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'java-compile-di')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: java/compile-di
      cmd: |
        ./test.sh --sample=java/compile-di --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  java-dagger2:
    name: "Java :: Dagger2"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'java-dagger2')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: java/dagger2
      cmd: |
        ./test.sh --sample=java/dagger2 --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  java-ebean:
    name: "Java :: EBean"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'java-ebean')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: java/ebean
      cmd: |
        ./test.sh --sample=java/ebean --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  java-fileupload:
    name: "Java :: File Upload"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'java-fileupload')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: java/fileupload
      cmd: |
        ./test.sh --sample=java/fileupload --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  java-forms:
    name: "Java :: Forms"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'java-forms')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: java/forms
      cmd: |
        ./test.sh --sample=java/forms --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  java-grpc:
    name: "Java :: gRPC"
    strategy:
      matrix:
        # Can't test with Java 21+ currently because of https://github.com/lightbend/ssl-config/issues/367
        java: [ 17 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'java-grpc')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: java/grpc
      cmd: |
        ./test.sh --sample=java/grpc --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  java-hello-world:
    name: "Java :: Hello World"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'java-hello-world')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: java/hello-world
      cmd: |
        ./test.sh --sample=java/hello-world --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  java-jpa:
    name: "Java :: JPA"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'java-jpa')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: java/jpa
      cmd: |
        ./test.sh --sample=java/jpa --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  java-pekko-cluster:
    name: "Java :: Pekko Cluster"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'java-pekko-cluster')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: java/pekko-cluster
      cmd: |
        ./test.sh --sample=java/pekko-cluster --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  java-rest-api:
    name: "Java :: REST API"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'java-rest-api')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: java/rest-api
      cmd: |
        ./test.sh --sample=java/rest-api --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  java-starter:
    name: "Java :: Starter"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'java-starter')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: java/starter
      cmd: |
        ./test.sh --sample=java/starter --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  java-streaming:
    name: "Java :: Streaming"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'java-streaming')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: java/streaming
      cmd: |
        ./test.sh --sample=java/streaming --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  java-websocket:
    name: "Java :: WebSocket"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'java-websocket')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: java/websocket
      cmd: |
        ./test.sh --sample=java/websocket --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  scala-anorm:
    name: "Scala :: Anorm"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'scala-anorm')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: scala/anorm
      cmd: |
        ./test.sh --sample=scala/anorm --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  scala-chatroom:
    name: "Scala :: Chatroom"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'scala-chatroom')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: scala/chatroom
      cmd: |
        ./test.sh --sample=scala/chatroom --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  scala-compile-di:
    name: "Scala :: Compile DI"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'scala-compile-di')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: scala/compile-di
      cmd: |
        ./test.sh --sample=scala/compile-di --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  scala-fileupload:
    name: "Scala :: File Upload"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'scala-fileupload')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: scala/fileupload
      cmd: |
        ./test.sh --sample=scala/fileupload --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  scala-forms:
    name: "Scala :: Forms"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'scala-forms')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: scala/forms
      cmd: |
        ./test.sh --sample=scala/forms --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  scala-grpc:
    name: "Scala :: gRPC"
    strategy:
      matrix:
        # Can't test with Java 21+ currently because of https://github.com/lightbend/ssl-config/issues/367
        java: [ 17 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'scala-grpc')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: scala/grpc
      cmd: |
        ./test.sh --sample=scala/grpc --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  scala-hello-world:
    name: "Scala :: Hello World"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'scala-hello-world')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: scala/hello-world
      cmd: |
        ./test.sh --sample=scala/hello-world --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  scala-isolated-slick:
    name: "Scala :: Slick (isolated)"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'scala-isolated-slick')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: scala/isolated-slick
      cmd: |
        ./test.sh --sample=scala/isolated-slick --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  scala-log4j2:
    name: "Scala :: Log4j2"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'scala-log4j2')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: scala/log4j2
      cmd: |
        ./test.sh --sample=scala/log4j2 --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  scala-macwire-di:
    name: "Scala :: Macwire DI"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'scala-macwire-di')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: scala/macwire-di
      cmd: |
        ./test.sh --sample=scala/macwire-di --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  scala-rest-api:
    name: "Scala :: REST API"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'scala-rest-api')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: scala/rest-api
      cmd: |
        ./test.sh --sample=scala/rest-api --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  scala-secure-session:
    name: "Scala :: Secure Session"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'scala-secure-session')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: scala/secure-session
      cmd: |
        ./test.sh --sample=scala/secure-session --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  scala-slick:
    name: "Scala :: Slick"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'scala-slick')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: scala/slick
      cmd: |
        ./test.sh --sample=scala/slick --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  scala-starter:
    name: "Scala :: Starter"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'scala-starter')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: scala/starter
      cmd: |
        ./test.sh --sample=scala/starter --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  scala-streaming:
    name: "Scala :: Streaming"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'scala-streaming')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: scala/streaming
      cmd: |
        ./test.sh --sample=scala/streaming --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  scala-tls:
    name: "Scala :: TLS"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'scala-tls')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: scala/tls
      cmd: |
        ./test.sh --sample=scala/tls --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  scala-websocket:
    name: "Scala :: WebSocket"
    strategy:
      matrix:
        java: [ 17, 21 ]
        scala: [ 2.13.x, 3.x ]
        server: [ pekko, netty ]
        build_tool: [ sbt, gradle ]
    uses: ihostage/.github-play/.github/workflows/cmd.yml@matrix
    needs: changes
    if: ${{ (github.event_name != 'pull_request' && !failure() && !cancelled()) || contains(fromJSON(needs.changes.outputs.samples), 'scala-websocket')}}
    with:
      java: ${{ matrix.java }}
      scala: ${{ matrix.scala }}
      gradle-build-root: scala/websocket
      cmd: |
        ./test.sh --sample=scala/websocket --backend-server=${{ matrix.server }} --build-tool=${{ matrix.build_tool }}

  finish:
    name: Finish
    if: ${{ github.event_name == 'pull_request' && !failure() && !cancelled() }}
    needs: # Should be last
      - "java-chatroom"
      - "java-compile-di"
      - "java-dagger2"
      - "java-ebean"
      - "java-fileupload"
      - "java-forms"
      - "java-grpc"
      - "java-hello-world"
      - "java-jpa"
      - "java-pekko-cluster"
      - "java-rest-api"
      - "java-starter"
      - "java-streaming"
      - "java-websocket"
      - "scala-anorm"
      - "scala-chatroom"
      - "scala-compile-di"
      - "scala-fileupload"
      - "scala-forms"
      - "scala-grpc"
      - "scala-hello-world"
      - "scala-isolated-slick"
      - "scala-log4j2"
      - "scala-macwire-di"
      - "scala-rest-api"
      - "scala-secure-session"
      - "scala-slick"
      - "scala-starter"
      - "scala-streaming"
      - "scala-tls"
      - "scala-websocket"
    uses: playframework/.github/.github/workflows/rtm.yml@v4
